name: ideapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1
  
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  uuid: ^4.5.2
  intl: ^0.20.2
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - demo.gif
